/* Automatically @generated by tree-sitter v0.25.8 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 69
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 42
#define ALIAS_COUNT 0
#define TOKEN_COUNT 25
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_SLASH_STAR = 1,
  aux_sym__multi_comment_token1 = 2,
  anon_sym_STAR_SLASH = 3,
  sym__single_comment = 4,
  sym_keyword = 5,
  sym_identifier = 6,
  sym_regex = 7,
  anon_sym_SQUOTE = 8,
  aux_sym__single_string_token1 = 9,
  anon_sym_DQUOTE = 10,
  aux_sym__double_string_token1 = 11,
  anon_sym_BQUOTE = 12,
  aux_sym__template_string_token1 = 13,
  anon_sym_LT = 14,
  aux_sym_jsx_start_token1 = 15,
  anon_sym_EQ = 16,
  anon_sym_GT = 17,
  anon_sym_SLASH_GT = 18,
  anon_sym_LT_SLASH = 19,
  aux_sym_jsx_end_token1 = 20,
  aux_sym_attribute_value_token1 = 21,
  anon_sym_LBRACE = 22,
  anon_sym_RBRACE = 23,
  sym_text = 24,
  sym_source_file = 25,
  aux_sym__js_context = 26,
  sym_comment = 27,
  sym__multi_comment = 28,
  sym_string = 29,
  sym__single_string = 30,
  sym__double_string = 31,
  sym__template_string = 32,
  sym_jsx_start = 33,
  sym__full_jsx = 34,
  sym_jsx_self = 35,
  sym_jsx_end = 36,
  sym_attribute_name = 37,
  sym_attribute_value = 38,
  sym_jsx_context = 39,
  aux_sym_jsx_start_repeat1 = 40,
  aux_sym__full_jsx_repeat1 = 41,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_SLASH_STAR] = "/*",
  [aux_sym__multi_comment_token1] = "_multi_comment_token1",
  [anon_sym_STAR_SLASH] = "*/",
  [sym__single_comment] = "_single_comment",
  [sym_keyword] = "keyword",
  [sym_identifier] = "identifier",
  [sym_regex] = "regex",
  [anon_sym_SQUOTE] = "'",
  [aux_sym__single_string_token1] = "_single_string_token1",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym__double_string_token1] = "_double_string_token1",
  [anon_sym_BQUOTE] = "`",
  [aux_sym__template_string_token1] = "_template_string_token1",
  [anon_sym_LT] = "<",
  [aux_sym_jsx_start_token1] = "jsx_start_token1",
  [anon_sym_EQ] = "=",
  [anon_sym_GT] = ">",
  [anon_sym_SLASH_GT] = "/>",
  [anon_sym_LT_SLASH] = "</",
  [aux_sym_jsx_end_token1] = "jsx_end_token1",
  [aux_sym_attribute_value_token1] = "attribute_value_token1",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_text] = "text",
  [sym_source_file] = "source_file",
  [aux_sym__js_context] = "_js_context",
  [sym_comment] = "comment",
  [sym__multi_comment] = "_multi_comment",
  [sym_string] = "string",
  [sym__single_string] = "_single_string",
  [sym__double_string] = "_double_string",
  [sym__template_string] = "_template_string",
  [sym_jsx_start] = "jsx_start",
  [sym__full_jsx] = "_full_jsx",
  [sym_jsx_self] = "jsx_self",
  [sym_jsx_end] = "jsx_end",
  [sym_attribute_name] = "attribute_name",
  [sym_attribute_value] = "attribute_value",
  [sym_jsx_context] = "jsx_context",
  [aux_sym_jsx_start_repeat1] = "jsx_start_repeat1",
  [aux_sym__full_jsx_repeat1] = "_full_jsx_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_SLASH_STAR] = anon_sym_SLASH_STAR,
  [aux_sym__multi_comment_token1] = aux_sym__multi_comment_token1,
  [anon_sym_STAR_SLASH] = anon_sym_STAR_SLASH,
  [sym__single_comment] = sym__single_comment,
  [sym_keyword] = sym_keyword,
  [sym_identifier] = sym_identifier,
  [sym_regex] = sym_regex,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym__single_string_token1] = aux_sym__single_string_token1,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym__double_string_token1] = aux_sym__double_string_token1,
  [anon_sym_BQUOTE] = anon_sym_BQUOTE,
  [aux_sym__template_string_token1] = aux_sym__template_string_token1,
  [anon_sym_LT] = anon_sym_LT,
  [aux_sym_jsx_start_token1] = aux_sym_jsx_start_token1,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_SLASH_GT] = anon_sym_SLASH_GT,
  [anon_sym_LT_SLASH] = anon_sym_LT_SLASH,
  [aux_sym_jsx_end_token1] = aux_sym_jsx_end_token1,
  [aux_sym_attribute_value_token1] = aux_sym_attribute_value_token1,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_text] = sym_text,
  [sym_source_file] = sym_source_file,
  [aux_sym__js_context] = aux_sym__js_context,
  [sym_comment] = sym_comment,
  [sym__multi_comment] = sym__multi_comment,
  [sym_string] = sym_string,
  [sym__single_string] = sym__single_string,
  [sym__double_string] = sym__double_string,
  [sym__template_string] = sym__template_string,
  [sym_jsx_start] = sym_jsx_start,
  [sym__full_jsx] = sym__full_jsx,
  [sym_jsx_self] = sym_jsx_self,
  [sym_jsx_end] = sym_jsx_end,
  [sym_attribute_name] = sym_attribute_name,
  [sym_attribute_value] = sym_attribute_value,
  [sym_jsx_context] = sym_jsx_context,
  [aux_sym_jsx_start_repeat1] = aux_sym_jsx_start_repeat1,
  [aux_sym__full_jsx_repeat1] = aux_sym__full_jsx_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SLASH_STAR] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__multi_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_STAR_SLASH] = {
    .visible = true,
    .named = false,
  },
  [sym__single_comment] = {
    .visible = false,
    .named = true,
  },
  [sym_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_regex] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__single_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__double_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_BQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__template_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_jsx_start_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_jsx_end_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_attribute_value_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__js_context] = {
    .visible = false,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__multi_comment] = {
    .visible = false,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym__single_string] = {
    .visible = false,
    .named = true,
  },
  [sym__double_string] = {
    .visible = false,
    .named = true,
  },
  [sym__template_string] = {
    .visible = false,
    .named = true,
  },
  [sym_jsx_start] = {
    .visible = true,
    .named = true,
  },
  [sym__full_jsx] = {
    .visible = false,
    .named = true,
  },
  [sym_jsx_self] = {
    .visible = true,
    .named = true,
  },
  [sym_jsx_end] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_name] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [sym_jsx_context] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_jsx_start_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__full_jsx_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 7,
  [9] = 6,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 24,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 27,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 26,
  [35] = 32,
  [36] = 20,
  [37] = 10,
  [38] = 11,
  [39] = 13,
  [40] = 14,
  [41] = 21,
  [42] = 17,
  [43] = 18,
  [44] = 23,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 52,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 61,
  [65] = 65,
  [66] = 66,
  [67] = 59,
  [68] = 57,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(13);
      ADVANCE_MAP(
        '"', 97,
        '\'', 94,
        '*', 4,
        '/', 2,
        '<', 105,
        '=', 107,
        '>', 108,
        '`', 101,
        'a', 77,
        'b', 75,
        'c', 24,
        'd', 34,
        'e', 55,
        'f', 65,
        'i', 43,
        'k', 37,
        'l', 35,
        'n', 36,
        'o', 44,
        'r', 38,
        's', 89,
        't', 90,
        'v', 25,
        'w', 48,
        '{', 113,
        '}', 114,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(19);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '*') ADVANCE(14);
      if (lookahead == '/') ADVANCE(1);
      if (lookahead == '>') ADVANCE(109);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(14);
      if (lookahead == '/') ADVANCE(1);
      if (lookahead == '\\') ADVANCE(10);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(5);
      END_STATE();
    case 4:
      if (lookahead == '/') ADVANCE(18);
      END_STATE();
    case 5:
      if (lookahead == '/') ADVANCE(93);
      if (lookahead == '\\') ADVANCE(10);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '/') ADVANCE(116);
      if (lookahead == '<') ADVANCE(105);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(117);
      if (lookahead != 0) ADVANCE(118);
      END_STATE();
    case 7:
      if (lookahead == '/') ADVANCE(8);
      if (lookahead == '=') ADVANCE(107);
      if (lookahead == '>') ADVANCE(108);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(7);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(111);
      END_STATE();
    case 8:
      if (lookahead == '>') ADVANCE(109);
      END_STATE();
    case 9:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(9);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(112);
      END_STATE();
    case 10:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(5);
      END_STATE();
    case 11:
      if (lookahead != 0 &&
          lookahead != '/') ADVANCE(17);
      END_STATE();
    case 12:
      if (eof) ADVANCE(13);
      ADVANCE_MAP(
        '"', 97,
        '\'', 94,
        '/', 3,
        '<', 104,
        '`', 101,
        'a', 77,
        'b', 75,
        'c', 24,
        'd', 34,
        'e', 55,
        'f', 65,
        'i', 43,
        'k', 37,
        'l', 35,
        'n', 36,
        'o', 44,
        'r', 38,
        's', 89,
        't', 90,
        'v', 25,
        'w', 48,
        '}', 114,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(12);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      if (lookahead != 0 &&
          lookahead != '<') ADVANCE(118);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(aux_sym__multi_comment_token1);
      if (lookahead == '*') ADVANCE(11);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(16);
      if (lookahead != 0) ADVANCE(17);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym__multi_comment_token1);
      if (lookahead == '*') ADVANCE(11);
      if (lookahead != 0) ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_STAR_SLASH);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym__single_comment);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym__single_comment);
      if (lookahead != 0 &&
          lookahead != '<') ADVANCE(118);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_keyword);
      if (lookahead == 't') ADVANCE(41);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_keyword);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(53);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(79);
      if (lookahead == 'l') ADVANCE(27);
      if (lookahead == 'o') ADVANCE(59);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(71);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(85);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(76);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(31);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'c') ADVANCE(47);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'c') ADVANCE(83);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'c') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(77);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(22);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(45);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(80);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(88);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(91);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(81);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(23);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(61);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(73);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(84);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'f') ADVANCE(22);
      if (lookahead == 'm') ADVANCE(69);
      if (lookahead == 'n') ADVANCE(21);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'f') ADVANCE(22);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'f') ADVANCE(26);
      if (lookahead == 'l') ADVANCE(42);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'f') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'h') ADVANCE(22);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'h') ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(56);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(82);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(62);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(67);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'k') ADVANCE(22);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(80);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(79);
      if (lookahead == 'x') ADVANCE(68);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'm') ADVANCE(22);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(22);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(78);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(30);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(87);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(57);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(71);
      if (lookahead == 'r') ADVANCE(64);
      if (lookahead == 'u') ADVANCE(60);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(72);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(58);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'p') ADVANCE(66);
      if (lookahead == 't') ADVANCE(40);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'p') ADVANCE(66);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'p') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(22);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(80);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(58);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(39);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(77);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(22);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(80);
      if (lookahead == 't') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(22);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(86);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(29);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(52);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(54);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(74);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'w') ADVANCE(22);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'w') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'y') ADVANCE(70);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'y') ADVANCE(63);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_regex);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(93);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(aux_sym__single_string_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(95);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(96);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(aux_sym__single_string_token1);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(96);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(aux_sym__double_string_token1);
      if (lookahead == '\\') ADVANCE(100);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(98);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(99);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(aux_sym__double_string_token1);
      if (lookahead == '\\') ADVANCE(100);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(99);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(aux_sym__double_string_token1);
      if (lookahead == '\\') ADVANCE(100);
      if (lookahead != 0) ADVANCE(99);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(anon_sym_BQUOTE);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(aux_sym__template_string_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(102);
      if (lookahead != 0 &&
          lookahead != '`') ADVANCE(103);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(aux_sym__template_string_token1);
      if (lookahead != 0 &&
          lookahead != '`') ADVANCE(103);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '/') ADVANCE(110);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(aux_sym_jsx_start_token1);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(anon_sym_SLASH_GT);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(anon_sym_LT_SLASH);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(aux_sym_jsx_end_token1);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(111);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(aux_sym_attribute_value_token1);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(112);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\n') ADVANCE(20);
      if (lookahead == '<') ADVANCE(1);
      if (lookahead != 0) ADVANCE(115);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '*') ADVANCE(15);
      if (lookahead == '/') ADVANCE(115);
      if (lookahead != 0 &&
          lookahead != '<') ADVANCE(118);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '/') ADVANCE(116);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(117);
      if (lookahead != 0 &&
          lookahead != '<') ADVANCE(118);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(sym_text);
      if (lookahead != 0 &&
          lookahead != '<') ADVANCE(118);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 12},
  [2] = {.lex_state = 12},
  [3] = {.lex_state = 12},
  [4] = {.lex_state = 12},
  [5] = {.lex_state = 12},
  [6] = {.lex_state = 6},
  [7] = {.lex_state = 6},
  [8] = {.lex_state = 6},
  [9] = {.lex_state = 6},
  [10] = {.lex_state = 12},
  [11] = {.lex_state = 12},
  [12] = {.lex_state = 12},
  [13] = {.lex_state = 12},
  [14] = {.lex_state = 12},
  [15] = {.lex_state = 12},
  [16] = {.lex_state = 12},
  [17] = {.lex_state = 12},
  [18] = {.lex_state = 12},
  [19] = {.lex_state = 6},
  [20] = {.lex_state = 12},
  [21] = {.lex_state = 12},
  [22] = {.lex_state = 12},
  [23] = {.lex_state = 12},
  [24] = {.lex_state = 106},
  [25] = {.lex_state = 106},
  [26] = {.lex_state = 7},
  [27] = {.lex_state = 7},
  [28] = {.lex_state = 6},
  [29] = {.lex_state = 7},
  [30] = {.lex_state = 6},
  [31] = {.lex_state = 7},
  [32] = {.lex_state = 7},
  [33] = {.lex_state = 6},
  [34] = {.lex_state = 7},
  [35] = {.lex_state = 7},
  [36] = {.lex_state = 6},
  [37] = {.lex_state = 6},
  [38] = {.lex_state = 6},
  [39] = {.lex_state = 6},
  [40] = {.lex_state = 6},
  [41] = {.lex_state = 6},
  [42] = {.lex_state = 6},
  [43] = {.lex_state = 6},
  [44] = {.lex_state = 6},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 7},
  [47] = {.lex_state = 7},
  [48] = {.lex_state = 7},
  [49] = {.lex_state = 7},
  [50] = {.lex_state = 7},
  [51] = {.lex_state = 7},
  [52] = {.lex_state = 7},
  [53] = {.lex_state = 7},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 16},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 95},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 98},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 102},
  [66] = {.lex_state = 9},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 16},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_SLASH_STAR] = ACTIONS(1),
    [anon_sym_STAR_SLASH] = ACTIONS(1),
    [sym__single_comment] = ACTIONS(1),
    [sym_keyword] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_BQUOTE] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_SLASH_GT] = ACTIONS(1),
    [anon_sym_LT_SLASH] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(54),
    [aux_sym__js_context] = STATE(3),
    [sym_comment] = STATE(3),
    [sym__multi_comment] = STATE(10),
    [sym_string] = STATE(3),
    [sym__single_string] = STATE(12),
    [sym__double_string] = STATE(12),
    [sym__template_string] = STATE(12),
    [sym_jsx_start] = STATE(7),
    [sym__full_jsx] = STATE(3),
    [sym_jsx_self] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
    [sym__single_comment] = ACTIONS(7),
    [sym_keyword] = ACTIONS(9),
    [sym_identifier] = ACTIONS(9),
    [sym_regex] = ACTIONS(11),
    [anon_sym_SQUOTE] = ACTIONS(13),
    [anon_sym_DQUOTE] = ACTIONS(15),
    [anon_sym_BQUOTE] = ACTIONS(17),
    [anon_sym_LT] = ACTIONS(19),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 13,
    ACTIONS(23), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(26), 1,
      sym__single_comment,
    ACTIONS(32), 1,
      sym_regex,
    ACTIONS(35), 1,
      anon_sym_SQUOTE,
    ACTIONS(38), 1,
      anon_sym_DQUOTE,
    ACTIONS(41), 1,
      anon_sym_BQUOTE,
    ACTIONS(44), 1,
      anon_sym_LT,
    STATE(7), 1,
      sym_jsx_start,
    STATE(10), 1,
      sym__multi_comment,
    ACTIONS(21), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(29), 2,
      sym_keyword,
      sym_identifier,
    STATE(12), 3,
      sym__single_string,
      sym__double_string,
      sym__template_string,
    STATE(2), 5,
      aux_sym__js_context,
      sym_comment,
      sym_string,
      sym__full_jsx,
      sym_jsx_self,
  [48] = 13,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(7), 1,
      sym__single_comment,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_BQUOTE,
    ACTIONS(19), 1,
      anon_sym_LT,
    ACTIONS(47), 1,
      ts_builtin_sym_end,
    ACTIONS(51), 1,
      sym_regex,
    STATE(7), 1,
      sym_jsx_start,
    STATE(10), 1,
      sym__multi_comment,
    ACTIONS(49), 2,
      sym_keyword,
      sym_identifier,
    STATE(12), 3,
      sym__single_string,
      sym__double_string,
      sym__template_string,
    STATE(2), 5,
      aux_sym__js_context,
      sym_comment,
      sym_string,
      sym__full_jsx,
      sym_jsx_self,
  [95] = 13,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(7), 1,
      sym__single_comment,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_BQUOTE,
    ACTIONS(19), 1,
      anon_sym_LT,
    ACTIONS(51), 1,
      sym_regex,
    ACTIONS(53), 1,
      anon_sym_RBRACE,
    STATE(7), 1,
      sym_jsx_start,
    STATE(10), 1,
      sym__multi_comment,
    ACTIONS(49), 2,
      sym_keyword,
      sym_identifier,
    STATE(12), 3,
      sym__single_string,
      sym__double_string,
      sym__template_string,
    STATE(2), 5,
      aux_sym__js_context,
      sym_comment,
      sym_string,
      sym__full_jsx,
      sym_jsx_self,
  [142] = 12,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(7), 1,
      sym__single_comment,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_BQUOTE,
    ACTIONS(19), 1,
      anon_sym_LT,
    ACTIONS(57), 1,
      sym_regex,
    STATE(7), 1,
      sym_jsx_start,
    STATE(10), 1,
      sym__multi_comment,
    ACTIONS(55), 2,
      sym_keyword,
      sym_identifier,
    STATE(12), 3,
      sym__single_string,
      sym__double_string,
      sym__template_string,
    STATE(4), 5,
      aux_sym__js_context,
      sym_comment,
      sym_string,
      sym__full_jsx,
      sym_jsx_self,
  [186] = 9,
    ACTIONS(59), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(61), 1,
      sym__single_comment,
    ACTIONS(63), 1,
      anon_sym_LT,
    ACTIONS(65), 1,
      anon_sym_LT_SLASH,
    ACTIONS(67), 1,
      sym_text,
    STATE(8), 1,
      sym_jsx_start,
    STATE(18), 1,
      sym_jsx_end,
    STATE(37), 1,
      sym__multi_comment,
    STATE(19), 4,
      sym_comment,
      sym__full_jsx,
      sym_jsx_self,
      aux_sym__full_jsx_repeat1,
  [217] = 9,
    ACTIONS(59), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(61), 1,
      sym__single_comment,
    ACTIONS(63), 1,
      anon_sym_LT,
    ACTIONS(65), 1,
      anon_sym_LT_SLASH,
    ACTIONS(69), 1,
      sym_text,
    STATE(8), 1,
      sym_jsx_start,
    STATE(13), 1,
      sym_jsx_end,
    STATE(37), 1,
      sym__multi_comment,
    STATE(6), 4,
      sym_comment,
      sym__full_jsx,
      sym_jsx_self,
      aux_sym__full_jsx_repeat1,
  [248] = 9,
    ACTIONS(59), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(61), 1,
      sym__single_comment,
    ACTIONS(63), 1,
      anon_sym_LT,
    ACTIONS(71), 1,
      anon_sym_LT_SLASH,
    ACTIONS(73), 1,
      sym_text,
    STATE(8), 1,
      sym_jsx_start,
    STATE(37), 1,
      sym__multi_comment,
    STATE(39), 1,
      sym_jsx_end,
    STATE(9), 4,
      sym_comment,
      sym__full_jsx,
      sym_jsx_self,
      aux_sym__full_jsx_repeat1,
  [279] = 9,
    ACTIONS(59), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(61), 1,
      sym__single_comment,
    ACTIONS(63), 1,
      anon_sym_LT,
    ACTIONS(67), 1,
      sym_text,
    ACTIONS(71), 1,
      anon_sym_LT_SLASH,
    STATE(8), 1,
      sym_jsx_start,
    STATE(37), 1,
      sym__multi_comment,
    STATE(43), 1,
      sym_jsx_end,
    STATE(19), 4,
      sym_comment,
      sym__full_jsx,
      sym_jsx_self,
      aux_sym__full_jsx_repeat1,
  [310] = 2,
    ACTIONS(77), 2,
      sym_keyword,
      sym_identifier,
    ACTIONS(75), 9,
      ts_builtin_sym_end,
      anon_sym_SLASH_STAR,
      sym__single_comment,
      sym_regex,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE,
      anon_sym_LT,
      anon_sym_RBRACE,
  [326] = 2,
    ACTIONS(81), 2,
      sym_keyword,
      sym_identifier,
    ACTIONS(79), 9,
      ts_builtin_sym_end,
      anon_sym_SLASH_STAR,
      sym__single_comment,
      sym_regex,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE,
      anon_sym_LT,
      anon_sym_RBRACE,
  [342] = 2,
    ACTIONS(85), 2,
      sym_keyword,
      sym_identifier,
    ACTIONS(83), 9,
      ts_builtin_sym_end,
      anon_sym_SLASH_STAR,
      sym__single_comment,
      sym_regex,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE,
      anon_sym_LT,
      anon_sym_RBRACE,
  [358] = 2,
    ACTIONS(89), 2,
      sym_keyword,
      sym_identifier,
    ACTIONS(87), 9,
      ts_builtin_sym_end,
      anon_sym_SLASH_STAR,
      sym__single_comment,
      sym_regex,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE,
      anon_sym_LT,
      anon_sym_RBRACE,
  [374] = 2,
    ACTIONS(93), 2,
      sym_keyword,
      sym_identifier,
    ACTIONS(91), 9,
      ts_builtin_sym_end,
      anon_sym_SLASH_STAR,
      sym__single_comment,
      sym_regex,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE,
      anon_sym_LT,
      anon_sym_RBRACE,
  [390] = 2,
    ACTIONS(97), 2,
      sym_keyword,
      sym_identifier,
    ACTIONS(95), 9,
      ts_builtin_sym_end,
      anon_sym_SLASH_STAR,
      sym__single_comment,
      sym_regex,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE,
      anon_sym_LT,
      anon_sym_RBRACE,
  [406] = 2,
    ACTIONS(101), 2,
      sym_keyword,
      sym_identifier,
    ACTIONS(99), 9,
      ts_builtin_sym_end,
      anon_sym_SLASH_STAR,
      sym__single_comment,
      sym_regex,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE,
      anon_sym_LT,
      anon_sym_RBRACE,
  [422] = 2,
    ACTIONS(105), 2,
      sym_keyword,
      sym_identifier,
    ACTIONS(103), 9,
      ts_builtin_sym_end,
      anon_sym_SLASH_STAR,
      sym__single_comment,
      sym_regex,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE,
      anon_sym_LT,
      anon_sym_RBRACE,
  [438] = 2,
    ACTIONS(109), 2,
      sym_keyword,
      sym_identifier,
    ACTIONS(107), 9,
      ts_builtin_sym_end,
      anon_sym_SLASH_STAR,
      sym__single_comment,
      sym_regex,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE,
      anon_sym_LT,
      anon_sym_RBRACE,
  [454] = 8,
    ACTIONS(111), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(114), 1,
      sym__single_comment,
    ACTIONS(117), 1,
      anon_sym_LT,
    ACTIONS(120), 1,
      anon_sym_LT_SLASH,
    ACTIONS(122), 1,
      sym_text,
    STATE(8), 1,
      sym_jsx_start,
    STATE(37), 1,
      sym__multi_comment,
    STATE(19), 4,
      sym_comment,
      sym__full_jsx,
      sym_jsx_self,
      aux_sym__full_jsx_repeat1,
  [482] = 2,
    ACTIONS(127), 2,
      sym_keyword,
      sym_identifier,
    ACTIONS(125), 9,
      ts_builtin_sym_end,
      anon_sym_SLASH_STAR,
      sym__single_comment,
      sym_regex,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE,
      anon_sym_LT,
      anon_sym_RBRACE,
  [498] = 2,
    ACTIONS(131), 2,
      sym_keyword,
      sym_identifier,
    ACTIONS(129), 9,
      ts_builtin_sym_end,
      anon_sym_SLASH_STAR,
      sym__single_comment,
      sym_regex,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE,
      anon_sym_LT,
      anon_sym_RBRACE,
  [514] = 2,
    ACTIONS(135), 2,
      sym_keyword,
      sym_identifier,
    ACTIONS(133), 9,
      ts_builtin_sym_end,
      anon_sym_SLASH_STAR,
      sym__single_comment,
      sym_regex,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE,
      anon_sym_LT,
      anon_sym_RBRACE,
  [530] = 2,
    ACTIONS(139), 2,
      sym_keyword,
      sym_identifier,
    ACTIONS(137), 9,
      ts_builtin_sym_end,
      anon_sym_SLASH_STAR,
      sym__single_comment,
      sym_regex,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE,
      anon_sym_LT,
      anon_sym_RBRACE,
  [546] = 6,
    ACTIONS(141), 1,
      aux_sym_jsx_start_token1,
    ACTIONS(143), 1,
      anon_sym_GT,
    ACTIONS(145), 1,
      anon_sym_SLASH_GT,
    ACTIONS(147), 1,
      aux_sym_jsx_end_token1,
    STATE(34), 1,
      aux_sym_jsx_start_repeat1,
    STATE(46), 1,
      sym_attribute_name,
  [565] = 6,
    ACTIONS(143), 1,
      anon_sym_GT,
    ACTIONS(147), 1,
      aux_sym_jsx_end_token1,
    ACTIONS(149), 1,
      aux_sym_jsx_start_token1,
    ACTIONS(151), 1,
      anon_sym_SLASH_GT,
    STATE(26), 1,
      aux_sym_jsx_start_repeat1,
    STATE(46), 1,
      sym_attribute_name,
  [584] = 5,
    ACTIONS(153), 1,
      anon_sym_GT,
    ACTIONS(155), 1,
      anon_sym_SLASH_GT,
    ACTIONS(157), 1,
      aux_sym_jsx_end_token1,
    STATE(31), 1,
      aux_sym_jsx_start_repeat1,
    STATE(46), 1,
      sym_attribute_name,
  [600] = 5,
    ACTIONS(157), 1,
      aux_sym_jsx_end_token1,
    ACTIONS(159), 1,
      anon_sym_GT,
    ACTIONS(161), 1,
      anon_sym_SLASH_GT,
    STATE(31), 1,
      aux_sym_jsx_start_repeat1,
    STATE(46), 1,
      sym_attribute_name,
  [616] = 1,
    ACTIONS(163), 5,
      anon_sym_SLASH_STAR,
      sym__single_comment,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      sym_text,
  [624] = 5,
    ACTIONS(157), 1,
      aux_sym_jsx_end_token1,
    ACTIONS(159), 1,
      anon_sym_GT,
    ACTIONS(165), 1,
      anon_sym_SLASH_GT,
    STATE(31), 1,
      aux_sym_jsx_start_repeat1,
    STATE(46), 1,
      sym_attribute_name,
  [640] = 1,
    ACTIONS(167), 5,
      anon_sym_SLASH_STAR,
      sym__single_comment,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      sym_text,
  [648] = 4,
    ACTIONS(171), 1,
      aux_sym_jsx_end_token1,
    STATE(31), 1,
      aux_sym_jsx_start_repeat1,
    STATE(46), 1,
      sym_attribute_name,
    ACTIONS(169), 2,
      anon_sym_GT,
      anon_sym_SLASH_GT,
  [662] = 5,
    ACTIONS(153), 1,
      anon_sym_GT,
    ACTIONS(157), 1,
      aux_sym_jsx_end_token1,
    ACTIONS(174), 1,
      anon_sym_SLASH_GT,
    STATE(29), 1,
      aux_sym_jsx_start_repeat1,
    STATE(46), 1,
      sym_attribute_name,
  [678] = 1,
    ACTIONS(176), 5,
      anon_sym_SLASH_STAR,
      sym__single_comment,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      sym_text,
  [686] = 5,
    ACTIONS(153), 1,
      anon_sym_GT,
    ACTIONS(157), 1,
      aux_sym_jsx_end_token1,
    ACTIONS(174), 1,
      anon_sym_SLASH_GT,
    STATE(31), 1,
      aux_sym_jsx_start_repeat1,
    STATE(46), 1,
      sym_attribute_name,
  [702] = 5,
    ACTIONS(153), 1,
      anon_sym_GT,
    ACTIONS(155), 1,
      anon_sym_SLASH_GT,
    ACTIONS(157), 1,
      aux_sym_jsx_end_token1,
    STATE(27), 1,
      aux_sym_jsx_start_repeat1,
    STATE(46), 1,
      sym_attribute_name,
  [718] = 1,
    ACTIONS(127), 5,
      anon_sym_SLASH_STAR,
      sym__single_comment,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      sym_text,
  [726] = 1,
    ACTIONS(77), 5,
      anon_sym_SLASH_STAR,
      sym__single_comment,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      sym_text,
  [734] = 1,
    ACTIONS(81), 5,
      anon_sym_SLASH_STAR,
      sym__single_comment,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      sym_text,
  [742] = 1,
    ACTIONS(89), 5,
      anon_sym_SLASH_STAR,
      sym__single_comment,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      sym_text,
  [750] = 1,
    ACTIONS(93), 5,
      anon_sym_SLASH_STAR,
      sym__single_comment,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      sym_text,
  [758] = 1,
    ACTIONS(131), 5,
      anon_sym_SLASH_STAR,
      sym__single_comment,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      sym_text,
  [766] = 1,
    ACTIONS(105), 5,
      anon_sym_SLASH_STAR,
      sym__single_comment,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      sym_text,
  [774] = 1,
    ACTIONS(109), 5,
      anon_sym_SLASH_STAR,
      sym__single_comment,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      sym_text,
  [782] = 1,
    ACTIONS(139), 5,
      anon_sym_SLASH_STAR,
      sym__single_comment,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      sym_text,
  [790] = 4,
    ACTIONS(178), 1,
      anon_sym_DQUOTE,
    ACTIONS(180), 1,
      anon_sym_LBRACE,
    STATE(48), 1,
      sym_attribute_value,
    STATE(49), 1,
      sym_jsx_context,
  [803] = 2,
    ACTIONS(182), 1,
      anon_sym_EQ,
    ACTIONS(184), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      aux_sym_jsx_end_token1,
  [812] = 1,
    ACTIONS(186), 4,
      anon_sym_EQ,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      aux_sym_jsx_end_token1,
  [819] = 1,
    ACTIONS(188), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      aux_sym_jsx_end_token1,
  [825] = 1,
    ACTIONS(190), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      aux_sym_jsx_end_token1,
  [831] = 1,
    ACTIONS(192), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      aux_sym_jsx_end_token1,
  [837] = 1,
    ACTIONS(194), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      aux_sym_jsx_end_token1,
  [843] = 2,
    ACTIONS(196), 1,
      anon_sym_GT,
    ACTIONS(198), 1,
      aux_sym_jsx_end_token1,
  [850] = 2,
    ACTIONS(200), 1,
      anon_sym_GT,
    ACTIONS(202), 1,
      aux_sym_jsx_end_token1,
  [857] = 1,
    ACTIONS(204), 1,
      ts_builtin_sym_end,
  [861] = 1,
    ACTIONS(206), 1,
      anon_sym_SQUOTE,
  [865] = 1,
    ACTIONS(208), 1,
      anon_sym_DQUOTE,
  [869] = 1,
    ACTIONS(210), 1,
      aux_sym__multi_comment_token1,
  [873] = 1,
    ACTIONS(212), 1,
      anon_sym_BQUOTE,
  [877] = 1,
    ACTIONS(214), 1,
      anon_sym_GT,
  [881] = 1,
    ACTIONS(216), 1,
      aux_sym__single_string_token1,
  [885] = 1,
    ACTIONS(218), 1,
      anon_sym_STAR_SLASH,
  [889] = 1,
    ACTIONS(220), 1,
      anon_sym_DQUOTE,
  [893] = 1,
    ACTIONS(222), 1,
      aux_sym__double_string_token1,
  [897] = 1,
    ACTIONS(224), 1,
      anon_sym_STAR_SLASH,
  [901] = 1,
    ACTIONS(226), 1,
      aux_sym__template_string_token1,
  [905] = 1,
    ACTIONS(228), 1,
      aux_sym_attribute_value_token1,
  [909] = 1,
    ACTIONS(230), 1,
      anon_sym_GT,
  [913] = 1,
    ACTIONS(232), 1,
      aux_sym__multi_comment_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 48,
  [SMALL_STATE(4)] = 95,
  [SMALL_STATE(5)] = 142,
  [SMALL_STATE(6)] = 186,
  [SMALL_STATE(7)] = 217,
  [SMALL_STATE(8)] = 248,
  [SMALL_STATE(9)] = 279,
  [SMALL_STATE(10)] = 310,
  [SMALL_STATE(11)] = 326,
  [SMALL_STATE(12)] = 342,
  [SMALL_STATE(13)] = 358,
  [SMALL_STATE(14)] = 374,
  [SMALL_STATE(15)] = 390,
  [SMALL_STATE(16)] = 406,
  [SMALL_STATE(17)] = 422,
  [SMALL_STATE(18)] = 438,
  [SMALL_STATE(19)] = 454,
  [SMALL_STATE(20)] = 482,
  [SMALL_STATE(21)] = 498,
  [SMALL_STATE(22)] = 514,
  [SMALL_STATE(23)] = 530,
  [SMALL_STATE(24)] = 546,
  [SMALL_STATE(25)] = 565,
  [SMALL_STATE(26)] = 584,
  [SMALL_STATE(27)] = 600,
  [SMALL_STATE(28)] = 616,
  [SMALL_STATE(29)] = 624,
  [SMALL_STATE(30)] = 640,
  [SMALL_STATE(31)] = 648,
  [SMALL_STATE(32)] = 662,
  [SMALL_STATE(33)] = 678,
  [SMALL_STATE(34)] = 686,
  [SMALL_STATE(35)] = 702,
  [SMALL_STATE(36)] = 718,
  [SMALL_STATE(37)] = 726,
  [SMALL_STATE(38)] = 734,
  [SMALL_STATE(39)] = 742,
  [SMALL_STATE(40)] = 750,
  [SMALL_STATE(41)] = 758,
  [SMALL_STATE(42)] = 766,
  [SMALL_STATE(43)] = 774,
  [SMALL_STATE(44)] = 782,
  [SMALL_STATE(45)] = 790,
  [SMALL_STATE(46)] = 803,
  [SMALL_STATE(47)] = 812,
  [SMALL_STATE(48)] = 819,
  [SMALL_STATE(49)] = 825,
  [SMALL_STATE(50)] = 831,
  [SMALL_STATE(51)] = 837,
  [SMALL_STATE(52)] = 843,
  [SMALL_STATE(53)] = 850,
  [SMALL_STATE(54)] = 857,
  [SMALL_STATE(55)] = 861,
  [SMALL_STATE(56)] = 865,
  [SMALL_STATE(57)] = 869,
  [SMALL_STATE(58)] = 873,
  [SMALL_STATE(59)] = 877,
  [SMALL_STATE(60)] = 881,
  [SMALL_STATE(61)] = 885,
  [SMALL_STATE(62)] = 889,
  [SMALL_STATE(63)] = 893,
  [SMALL_STATE(64)] = 897,
  [SMALL_STATE(65)] = 901,
  [SMALL_STATE(66)] = 905,
  [SMALL_STATE(67)] = 909,
  [SMALL_STATE(68)] = 913,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__js_context, 2, 0, 0),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__js_context, 2, 0, 0), SHIFT_REPEAT(57),
  [26] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__js_context, 2, 0, 0), SHIFT_REPEAT(10),
  [29] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__js_context, 2, 0, 0), SHIFT_REPEAT(2),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__js_context, 2, 0, 0), SHIFT_REPEAT(2),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__js_context, 2, 0, 0), SHIFT_REPEAT(60),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__js_context, 2, 0, 0), SHIFT_REPEAT(63),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__js_context, 2, 0, 0), SHIFT_REPEAT(65),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__js_context, 2, 0, 0), SHIFT_REPEAT(24),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [55] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [63] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [65] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [67] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [69] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [71] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [73] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 1, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 1, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jsx_self, 2, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_jsx_self, 2, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 1, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 1, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__full_jsx, 2, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__full_jsx, 2, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__multi_comment, 3, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__multi_comment, 3, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__double_string, 3, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__double_string, 3, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__single_string, 3, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__single_string, 3, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jsx_end, 2, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_jsx_end, 2, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__full_jsx, 3, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__full_jsx, 3, 0, 0),
  [111] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__full_jsx_repeat1, 2, 0, 0), SHIFT_REPEAT(68),
  [114] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__full_jsx_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [117] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__full_jsx_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__full_jsx_repeat1, 2, 0, 0),
  [122] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__full_jsx_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jsx_end, 3, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_jsx_end, 3, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jsx_self, 3, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_jsx_self, 3, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__template_string, 3, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__template_string, 3, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jsx_self, 4, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_jsx_self, 4, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [143] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [145] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [147] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [151] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [163] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_jsx_start, 3, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [167] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_jsx_start, 4, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_jsx_start_repeat1, 2, 0, 0),
  [171] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_jsx_start_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [176] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_jsx_start, 2, 0, 0),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_jsx_start_repeat1, 1, 0, 0),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_name, 1, 0, 0),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_jsx_start_repeat1, 3, 0, 0),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_value, 1, 0, 0),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jsx_context, 3, 0, 0),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_value, 3, 0, 0),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [204] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_javascript(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "javascript",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
